### ISSUE TITLE
[5.0.3] Templates order by "Mod Date" exception

### ISSUE THREAD

**Issue by Djacomo** [dotCMS/core-web#912] opened 2019-01-19 15:25 UTC
Ordering Templates by "Mod. Date" get an exception:

```
An unexpected system error occurred.com.dotmarketing.exception.DotDataException: ERROR: column asset.moddate does not exist Hint: Perhaps you meant to reference the column "asset.mod_date". Position: 392{ "SQL": ["select asset.*, inode.* from template asset, inode, identifier, template_version_info versioninfo where asset.inode = inode.inode and asset.identifier = identifier.id and versioninfo.identifier=asset.identifier and show_on_menu = 'true' and identifier.host_inode = '48190c8c-42c4-46af-8d1a-0cd5db894797' and asset.inode=versioninfo.working_inode and versioninfo.deleted = 'false' order by asset.modDate desc"], "maxRows": [500], "offest": [0] }
--

```
URL for reproduce: https://demo.dotcms.com/dotAdmin/#/c/templates

**Comment by wezell** [comment] 2019-01-20 17:16
dupe of #15708. I will close this one.

**Closed** 2019-12-19 21:24 UTC
